#!/usr/bin/env python3
"""YOUSPEAK Pipeline — discover.

Finds gaps via cross-tradition overlay. Given a concept name, surveys
the archaeology/ directory for files touching that concept's semantic
field, extracts each tradition's coverage notes, and produces a gap-
analysis template for the Forge.

Usage:
    python3 discover.py <concept>           survey archaeology; produce gap-template
    python3 discover.py --list              list all archaeology files with semantic_field
    python3 discover.py --seed <tongue>     stub a new archaeology tradition directory
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARCH_DIR = ROOT / "archaeology"
FORGE_DIR = ROOT / "labs" / "logos" / "forge"


def _frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    fm: dict = {}
    for line in parts[1].strip().splitlines():
        m = re.match(r"^([\w_]+):\s*(.*)$", line)
        if m:
            fm[m.group(1)] = m.group(2).strip()
    return fm


def survey_archaeology() -> list[dict]:
    """Walk archaeology/ and return a list of {tongue, semantic_field, path}."""
    if not ARCH_DIR.is_dir():
        return []
    out: list[dict] = []
    for md in sorted(ARCH_DIR.rglob("*.md")):
        try:
            fm = _frontmatter(md.read_text())
        except Exception:
            continue
        out.append({
            "tongue": fm.get("tongue", md.parent.name),
            "semantic_field": fm.get("semantic_field", "—"),
            "path": str(md.relative_to(ROOT)),
            "status": fm.get("status", ""),
        })
    return out


def cmd_list() -> int:
    rows = survey_archaeology()
    if not rows:
        print("(no archaeology files)")
        return 0
    print(f"{'tongue':30s} {'semantic_field':40s} path")
    for r in rows:
        print(f"{r['tongue']:30s} {r['semantic_field']:40s} {r['path']}")
    return 0


def cmd_survey(concept: str) -> int:
    """Produce a gap-analysis template for a concept.

    Matches archaeology files whose semantic_field contains the concept
    (case-insensitive substring). Emits a gap-template with one row per
    matched tradition.
    """
    concept_lc = concept.lower()
    rows = survey_archaeology()
    matches = [r for r in rows if concept_lc in r["semantic_field"].lower()]
    non_matches = [r for r in rows if concept_lc not in r["semantic_field"].lower()]

    template_name = concept.lower().replace(" ", "-") + "-gap.md"
    out_path = FORGE_DIR / template_name

    today = date.today().isoformat()
    lines = [
        f"---",
        f"id: {out_path.stem}",
        f"phase: GAP-ANALYSIS",
        f"concept: {concept}",
        f"opened: {today}",
        f"archaeology_matched: {len(matches)}",
        f"archaeology_total_surveyed: {len(rows)}",
        f"---",
        "",
        f"# Gap Analysis — {concept}",
        "",
        f"_Cross-tradition overlay for: **{concept}**._",
        "",
        "---",
        "",
        "## Traditions with direct coverage",
        "",
    ]
    if matches:
        lines.append("| Tongue | Semantic Field | Archaeology File |")
        lines.append("|---|---|---|")
        for r in matches:
            lines.append(f"| {r['tongue']} | {r['semantic_field']} | [{r['path']}]({r['path']}) |")
    else:
        lines.append("_(no archaeology files with matching semantic_field)_")
    lines += [
        "",
        "## 5-quality specification (to be filled by the forger)",
        "",
        "| Q | Requirement |",
        "|---|---|",
        "| Q1 | ... |",
        "| Q2 | ... |",
        "| Q3 | ... |",
        "| Q4 | ... |",
        "| Q5 | ... |",
        "",
        "## Neighbour map (to be filled per matched tradition)",
        "",
        "| Tradition | Word | Covers | Fails on |",
        "|---|---|---|---|",
    ]
    for r in matches:
        lines.append(f"| {r['tongue']} | ... | ... | ... |")
    lines += [
        "",
        "## Negative space",
        "",
        "_What the traditions circle but do not name. Decisive axis for the forge._",
        "",
        "## Candidates to forge",
        "",
        "_Ranked by gap-fit. Proceed to experiments/NNN-<candidate>.md for each._",
        "",
        "---",
        "",
        f"_Generated by discover.py on {today}. Nuance fills in the specification and neighbour map before forging begins._",
    ]

    FORGE_DIR.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        print(f"error: {out_path.name} already exists; remove or rename manually", file=sys.stderr)
        return 1
    out_path.write_text("\n".join(lines))
    print(f"stubbed: {out_path}")
    print(f"  matched traditions: {len(matches)}")
    print(f"  non-matches: {len(non_matches)}")
    return 0


def cmd_seed(tongue: str) -> int:
    """Stub a new archaeology tradition directory with a placeholder file."""
    tongue_dir = ARCH_DIR / tongue.lower().replace(" ", "_").replace("-", "_")
    tongue_dir.mkdir(parents=True, exist_ok=True)
    # Emit a README placeholder so the dir is tracked
    readme = tongue_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            f"# {tongue} archaeology\n\n"
            f"_Seed directory. Each semantic-field file goes here with frontmatter:\n"
            f"`tongue`, `semantic_field`, `excavated`, `status`._\n"
        )
    print(f"seeded: {tongue_dir}")
    return 0


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    arg = sys.argv[1]
    if arg == "--list":
        return cmd_list()
    if arg == "--seed" and len(sys.argv) >= 3:
        return cmd_seed(sys.argv[2])
    return cmd_survey(arg)


if __name__ == "__main__":
    sys.exit(main())
