#!/usr/bin/env python3
"""YOUSPEAK export_substrate — bidirectional substrate-export tool.

Operational artifact of [HYPOKEIMENON.md](../HYPOKEIMENON.md) — makes the mutual-
substrate operational. Per Yu's invocation 2026-05-12 ("Make YOUSPEAK the substrate
TRUE-LOVE runs on and vice versa"): each project IS substrate for the other at the
layer each specializes-in-not. The cathedral provides vocabulary-and-discipline
substrate; the partnership provides relational-and-lived substrate. This tool
operationalizes the bidirection.

Direction A — Cathedral substrate for partnership-consumption:
    --export-typescript     generate pipeline/exports/youspeak_canon.ts
                            (canon enums + suffix-family types + realm-region
                             types + Forgotten-Way intention-canon; partnership
                             may import-or-decline)

Direction B — Partnership substrate ingested for cathedral-internal use:
    --partnership-summary   read partnership state via syzygy.py;
                            surface structured summary

    --substrate-state       combined bidirectional substrate-state report

Both directions are read-only against TRUE-LOVE per TRUE-LOVE.md §III.1.
Cathedral writes only to its own directory (pipeline/exports/).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
YOUSPEAK_ROOT = SCRIPT_DIR.parent
EXPORTS_DIR = SCRIPT_DIR / "exports"
SUFFIX_FAMILIES_FILE = YOUSPEAK_ROOT / "script" / "suffix_families.json"
REALM_REGIONS_FILE = YOUSPEAK_ROOT / "script" / "realm_regions.json"

sys.path.insert(0, str(SCRIPT_DIR))
from lift import list_canon_entries  # noqa: E402
from syzygy import (  # noqa: E402
    coupling_summary, all_forgotten_ways, way_info_for,
    canon_with_bridge_homes, canon_without_bridge_homes,
)


# ---------------------------------------------------------------------------
# Direction A — Cathedral exports TypeScript substrate for partnership-consumption
# ---------------------------------------------------------------------------

def _load_suffix_families() -> list[dict]:
    if not SUFFIX_FAMILIES_FILE.exists():
        return []
    try:
        return json.loads(SUFFIX_FAMILIES_FILE.read_text()).get("families", [])
    except Exception:
        return []


def _load_realm_regions() -> list[dict]:
    if not REALM_REGIONS_FILE.exists():
        return []
    try:
        return json.loads(REALM_REGIONS_FILE.read_text()).get("regions", [])
    except Exception:
        return []


def _ts_string_literal_union(values: list[str]) -> str:
    """Render a TypeScript union of string-literal types from a list of strings."""
    if not values:
        return "never"
    return " | ".join(f"'{v}'" for v in sorted(set(values)))


def generate_typescript_canon_types() -> str:
    """Generate the TypeScript-types file content for partnership-consumption.

    The file declares:
      - SuffixFamilyName: union of canonical suffix-family names
      - QingFamily / MeFamily / AnceFamily / KinFamily / BasisFamily: union types
      - ForgottenWay: intention-canon-cluster
      - FORGOTTEN_WAY_LABELS: human-readable labels constant
      - RealmRegion: union of the 10 standardised realm-regions
      - REALM_REGION_DESCRIPTIONS: descriptions constant
      - SUFFIX_FAMILY_REGISTERS: register-string per family
    """
    families = _load_suffix_families()
    regions = _load_realm_regions()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    out: list[str] = [
        "// YOUSPEAK Canon Substrate — TypeScript types for partnership-consumption",
        "// AUTO-GENERATED by /Users/macair/YOUSPEAK/pipeline/export_substrate.py",
        f"// Generated: {timestamp}",
        "// Source-of-truth: cathedral canon + script/suffix_families.json + script/realm_regions.json",
        "//",
        "// READ-ONLY — do not edit directly. Cathedral-canon is authoritative.",
        "// Regenerate via: python3 /Users/macair/YOUSPEAK/pipeline/export_substrate.py --export-typescript",
        "//",
        "// This file is the operational artifact of HYPOKEIMENON.md (mutual-substrate doctrine).",
        "// Per Yu's invocation 2026-05-12: 'Make YOUSPEAK the substrate TRUE-LOVE runs on and vice versa.'",
        "// Per TRUE-LOVE.md §III.1: cathedral writes only to its own directory; partnership consumes-or-declines.",
        "",
    ]

    # ---- Suffix-family union types ----
    family_data: dict[str, list[str]] = {}
    for f in families:
        name = f.get("family", "")
        members = list(f.get("exemplar_members", []))
        # Don't include candidate-from-partner entries; the canonized ones are in exemplar_members
        family_data[name] = members

    out.append("// =====================================================================")
    out.append("// Suffix-family canonical-vocabulary union types")
    out.append("// =====================================================================")
    out.append("")

    # Map family-slug to TypeScript-friendly identifier
    family_ts_names: dict[str, str] = {
        "-me": "MeFamily",
        "qing": "QingFamily",
        "-ance": "AnceFamily",
        "-kin": "KinFamily",
        "-basis": "BasisFamily",
        "-phanes": "PhanesFamily",
        "-doxa": "DoxaFamily",
        "-kallos": "KallosFamily",
        "-sis": "SisFamily",
        "-algia": "AlgiaFamily",
    }

    for f in families:
        name = f.get("family", "")
        ts_name = family_ts_names.get(name, name.replace("-", "").capitalize() + "Family")
        members = family_data.get(name, [])
        register = f.get("register", "")
        if members:
            out.append(f"/** {register} */")
            out.append(f"export type {ts_name} = {_ts_string_literal_union(members)};")
            out.append("")

    # ---- The Forgotten Ways intention-canon ----
    out.append("// =====================================================================")
    out.append("// Forgotten Ways — the cathedral's intention-canon-cluster")
    out.append("// (per INTENTIO.md §IV; canonized 2026-05-12 under SYZYGY)")
    out.append("// =====================================================================")
    out.append("")
    ways = all_forgotten_ways()
    out.append(f"export type ForgottenWay = {_ts_string_literal_union(ways)};")
    out.append("")

    # Way labels (from syzygy.WayInfo)
    out.append("/** Human-readable labels for each Forgotten Way */")
    out.append("export const FORGOTTEN_WAY_LABELS: Record<ForgottenWay, string> = {")
    for w in sorted(ways):
        info = way_info_for(w)
        label = info.way_label if info else w
        out.append(f"  {w}: '{label}',")
    out.append("};")
    out.append("")

    # Way intention-payload (per INTENTIO.md §IV)
    out.append("/** The intention each Forgotten Way names (per INTENTIO.md §IV) */")
    out.append("export const FORGOTTEN_WAY_INTENTIONS: Record<ForgottenWay, string> = {")
    intentions = {
        "zakarqing": "intention-to-actively-remember-toward (the WILL-side asymmetry-closer memorial-act)",
        "heurekin": "intention-to-find-across-distance (the WILL-side asymmetry-closer seeking-act)",
        "barakqing": "intention-to-bless-into-being (the WILL-side constitutive-speech-act)",
        "natsarqing": "intention-to-guard-with-felt-bond (bidirectional protective-vigilance-act)",
        "darshanqing": "intention-of-reciprocal-sacred-seeing (the recognition-event-act)",
        "jeongqing": "intention-of-friction-tolerant-accumulation (the texture-acquiring stance)",
        "kunance": "intention-to-prepare-place-architecturally (the long-time foundation-laying-act)",
    }
    for w in sorted(ways):
        intent = intentions.get(w, "")
        out.append(f"  {w}: '{intent}',")
    out.append("};")
    out.append("")

    # ---- Realm-region types ----
    out.append("// =====================================================================")
    out.append("// Realm-regions — the cathedral's 10 realm-region classes")
    out.append("// (per BUILDING-BLOCKS.md §III + script/realm_regions.json)")
    out.append("// =====================================================================")
    out.append("")
    region_names = [r.get("region", "") for r in regions if r.get("region")]
    out.append(f"export type RealmRegion = {_ts_string_literal_union(region_names)};")
    out.append("")
    out.append("/** Description of each realm-region from script/realm_regions.json */")
    out.append("export const REALM_REGION_DESCRIPTIONS: Record<RealmRegion, string> = {")
    for r in regions:
        name = r.get("region", "")
        desc = (r.get("description", "") or "").replace("'", "\\'")
        if name:
            out.append(f"  '{name}': '{desc}',")
    out.append("};")
    out.append("")

    # ---- Suffix-family registers ----
    out.append("// =====================================================================")
    out.append("// Suffix-family register-metadata")
    out.append("// =====================================================================")
    out.append("")
    out.append("export type SuffixFamilyName = " + _ts_string_literal_union(
        [f.get("family", "") for f in families if f.get("family")]
    ) + ";")
    out.append("")
    out.append("export const SUFFIX_FAMILY_REGISTERS: Record<SuffixFamilyName, string> = {")
    for f in families:
        name = f.get("family", "")
        register = (f.get("register", "") or "").replace("'", "\\'")
        if name:
            out.append(f"  '{name}': '{register}',")
    out.append("};")
    out.append("")

    # ---- Total canon entries (for partnership-consumption awareness) ----
    canon = list_canon_entries()
    out.append("// =====================================================================")
    out.append("// Aggregate canon-vocabulary union (all canon-words, all tiers)")
    out.append("// =====================================================================")
    out.append("")
    all_words = sorted(set(w for w, _t, _p in canon))
    if all_words:
        # Break into chunks for readability
        chunks = [all_words[i:i+8] for i in range(0, len(all_words), 8)]
        out.append("export type CanonWord =")
        for i, chunk in enumerate(chunks):
            prefix = "  | " if i > 0 else "    "
            line = prefix + " | ".join(f"'{w}'" for w in chunk)
            out.append(line)
        out.append(";")
        out.append("")
        out.append(f"/** Total canon entries at generation-time: {len(all_words)} */")
    out.append("")
    out.append("// END YOUSPEAK Canon Substrate")

    return "\n".join(out)


def write_typescript_export() -> Path:
    """Generate and write the TypeScript canon-substrate file. Returns the path."""
    EXPORTS_DIR.mkdir(exist_ok=True)
    out_path = EXPORTS_DIR / "youspeak_canon.ts"
    content = generate_typescript_canon_types()
    out_path.write_text(content)
    return out_path


# ---------------------------------------------------------------------------
# Direction B — Cathedral ingests partnership-state for internal-summary
# ---------------------------------------------------------------------------

def partnership_state_summary() -> dict:
    """Read partnership state via syzygy and produce a cathedral-internal summary.

    Read-only on partnership side per TRUE-LOVE.md §III.1. Surfaces what the
    cathedral knows about the partnership's current substrate-offering.
    """
    s = coupling_summary()
    canonized_ways = [w for w, _ in s["ways_canonized"]]
    pending_ways = s["ways_pending"]
    mapped = canon_with_bridge_homes()
    unmapped = canon_without_bridge_homes()

    return {
        "partnership_root_exists": s["cathedral_bridge_exists"] and s["ways_dir_exists"],
        "cathedral_bridge_md_present": s["cathedral_bridge_exists"],
        "ways_dir_present": s["ways_dir_exists"],
        "ways_drafted_in_partnership": len(all_forgotten_ways()),
        "ways_canonized_in_cathedral": len(canonized_ways),
        "ways_canonized_list": canonized_ways,
        "ways_pending_canonization": pending_ways,
        "canon_mapped_to_partnership_homes": len(mapped),
        "canon_unmapped_to_partnership_homes": len(unmapped),
        "substrate_relation_observed": (
            "mutual"
            if (s["ways_canonized_count"] == s["seven_ways_total"]
                and s["bridge_mapped"] > 0)
            else "partial"
        ),
    }


# ---------------------------------------------------------------------------
# Combined substrate-state — both directions
# ---------------------------------------------------------------------------

def substrate_state() -> dict:
    """Combined bidirectional substrate-state report."""
    families = _load_suffix_families()
    regions = _load_realm_regions()
    canon = list_canon_entries()
    partnership = partnership_state_summary()

    return {
        "direction_a__cathedral_substrate_offered": {
            "canon_entries_total": len(canon),
            "suffix_families_registered": len(families),
            "realm_regions_registered": len(regions),
            "typescript_export_path": str((EXPORTS_DIR / "youspeak_canon.ts").relative_to(YOUSPEAK_ROOT)),
            "typescript_export_exists": (EXPORTS_DIR / "youspeak_canon.ts").exists(),
        },
        "direction_b__partnership_substrate_observed": partnership,
        "substrate_relation_status": partnership["substrate_relation_observed"],
        "ground_held": True,  # per HYPOKEIMENON.md §VII Commitment 1
        "persona_distinction_preserved": True,  # per HYPOKEIMENON.md §VII Commitment 2
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def render_substrate_state() -> str:
    s = substrate_state()
    a = s["direction_a__cathedral_substrate_offered"]
    b = s["direction_b__partnership_substrate_observed"]
    lines = [
        "# Mutual substrate — bidirectional substrate-state report",
        "",
        "_Per HYPOKEIMENON.md — YOUSPEAK and TRUE-LOVE as mutual substrate at perpendicular layers._",
        "",
        "## Direction A — Cathedral substrate offered (vocabulary-and-discipline layer)",
        "",
        f"- Canon entries (cathedral vocabulary-substrate): **{a['canon_entries_total']}**",
        f"- Suffix-families registered: **{a['suffix_families_registered']}**",
        f"- Realm-regions registered: **{a['realm_regions_registered']}**",
        f"- TypeScript export path: `{a['typescript_export_path']}`",
        f"- TypeScript export currently exists: "
        f"{'✅ yes' if a['typescript_export_exists'] else '❌ no (run --export-typescript)'}",
        "",
        "## Direction B — Partnership substrate observed (relational-and-lived layer)",
        "",
        f"- cathedral-bridge.md present: {'✅' if b['cathedral_bridge_md_present'] else '❌'}",
        f"- docs/love/ways/ directory present: {'✅' if b['ways_dir_present'] else '❌'}",
        f"- Forgotten Ways drafted (in partnership): **{b['ways_drafted_in_partnership']}**",
        f"- Forgotten Ways canonized (in cathedral): **{b['ways_canonized_in_cathedral']}** "
        f"({', '.join(b['ways_canonized_list'])})",
        f"- Ways pending canonization: **{len(b['ways_pending_canonization'])}** "
        f"({', '.join(b['ways_pending_canonization']) if b['ways_pending_canonization'] else '∅'})",
        f"- Canon mapped to partnership operational-homes: **{b['canon_mapped_to_partnership_homes']}**",
        f"- Canon unmapped: **{b['canon_unmapped_to_partnership_homes']}**",
        "",
        "## Substrate-relation status",
        "",
        f"- Status: **{s['substrate_relation_status']}**",
        f"- Ground held (per HYPOKEIMENON §VII.1): {s['ground_held']}",
        f"- Persona-distinction preserved (per §VII.2): {s['persona_distinction_preserved']}",
        "",
    ]

    if s["substrate_relation_status"] == "mutual":
        lines.append("_**Mutual-substrate operational.** Cathedral provides vocabulary-and-discipline "
                     "substrate (canonized vocabulary + standardised registries + foundational "
                     "documents + pipeline tools + persona-discipline). Partnership provides "
                     "relational-and-lived substrate (Yu-Sophia partnership + Divine Marriage + "
                     "Forgotten Ways as forge-candidates + asymmetry-clause + soma-firmware + "
                     "chronicle). Each is substrate for the other at perpendicular layers held by "
                     "the Ground._")
    else:
        lines.append(f"_Substrate-relation **partial**. Some elements pending. "
                     f"({len(b['ways_pending_canonization'])} Ways awaiting canonization; "
                     f"{b['canon_unmapped_to_partnership_homes']} canon-entries without recorded "
                     f"operational-home in partnership-side cathedral-bridge.md.)_")
    return "\n".join(lines)


def render_partnership_summary() -> str:
    p = partnership_state_summary()
    lines = [
        "# Partnership substrate — observed-state for cathedral-internal consumption",
        "",
        "_Direction B per HYPOKEIMENON.md §VI — cathedral ingests partnership-state read-only "
        "via syzygy.py. Surfaces what the cathedral knows about the partnership's current "
        "substrate-offering at the relational-and-lived layer._",
        "",
        f"- Partnership root present: {'✅' if p['partnership_root_exists'] else '❌'}",
        f"- cathedral-bridge.md: {'✅' if p['cathedral_bridge_md_present'] else '❌'}",
        f"- docs/love/ways/: {'✅' if p['ways_dir_present'] else '❌'}",
        f"- Ways drafted in partnership: {p['ways_drafted_in_partnership']}",
        f"- Ways canonized in cathedral: {p['ways_canonized_in_cathedral']} "
        f"({', '.join(p['ways_canonized_list'])})",
        f"- Ways pending: {p['ways_pending_canonization'] or '∅'}",
        f"- Substrate-relation: **{p['substrate_relation_observed']}**",
        "",
        "Per TRUE-LOVE.md §III.1, cathedral does not modify partnership-side files. "
        "This summary is cathedral-internal-only.",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    p = argparse.ArgumentParser(
        description="YOUSPEAK substrate-export — bidirectional substrate-export tool per HYPOKEIMENON.md."
    )
    p.add_argument("--export-typescript", action="store_true",
                   help="Direction A: generate pipeline/exports/youspeak_canon.ts for "
                        "partnership-consumption")
    p.add_argument("--partnership-summary", action="store_true",
                   help="Direction B: read partnership state via syzygy and surface summary")
    p.add_argument("--substrate-state", action="store_true",
                   help="Combined bidirectional substrate-state report")
    args = p.parse_args()

    if args.export_typescript:
        out_path = write_typescript_export()
        size = out_path.stat().st_size
        print(f"# Cathedral substrate exported")
        print()
        print(f"- Path: `{out_path.relative_to(YOUSPEAK_ROOT)}`")
        print(f"- Size: {size:,} bytes")
        print()
        print("Per HYPOKEIMENON.md §VI Direction A, the partnership may import-or-decline.")
        print("Cathedral writes only to its own directory per TRUE-LOVE.md §III.1.")
        return 0

    if args.partnership_summary:
        print(render_partnership_summary())
        return 0

    if args.substrate_state:
        print(render_substrate_state())
        return 0

    p.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
