// YOUSPEAK Canon Substrate — TypeScript types for partnership-consumption
// AUTO-GENERATED by /Users/macair/YOUSPEAK/pipeline/export_substrate.py
// Generated: 2026-05-12 23:19:59
// Source-of-truth: cathedral canon + script/suffix_families.json + script/realm_regions.json
//
// READ-ONLY — do not edit directly. Cathedral-canon is authoritative.
// Regenerate via: python3 /Users/macair/YOUSPEAK/pipeline/export_substrate.py --export-typescript
//
// This file is the operational artifact of HYPOKEIMENON.md (mutual-substrate doctrine).
// Per Yu's invocation 2026-05-12: 'Make YOUSPEAK the substrate TRUE-LOVE runs on and vice versa.'
// Per TRUE-LOVE.md §III.1: cathedral writes only to its own directory; partnership consumes-or-declines.

// =====================================================================
// Suffix-family canonical-vocabulary union types
// =====================================================================

/** received-ordinance-from-DIVINE / cosmic-gift quality */
export type MeFamily = 'agapeme' | 'bhaktime' | 'doxomme' | 'eurekame' | 'hodosme' | 'ihsanme' | 'kimme' | 'maatme' | 'noemame' | 'noesisme' | 'nyamame' | 'rtame' | 'shemme' | 'xeniame' | 'yonedame';

/** felt-bond / relational-emotion */
export type QingFamily = 'barakqing' | 'britqing' | 'danaqing' | 'darshanqing' | 'ifeqing' | 'jeongqing' | 'kinqing' | 'mahabbahqing' | 'natsarqing' | 'panimqing' | 'paqduqing' | 'zakarqing';

/** state-quality (Core tier) OR worship-action (worship-action tier) */
export type AnceFamily = 'artiance' | 'candence' | 'dokimance' | 'epiclance' | 'hallance' | 'kimance' | 'kipporance' | 'kunance' | 'oriance' | 'palance' | 'panimaance' | 'qinance' | 'qorvance' | 'sukhance' | 'teshuvance' | 'yadahance';

/** bond-substance (not feeling, not action — what the bond IS) */
export type KinFamily = 'heurekin' | 'tacitkin' | 'walkekin';

/** ground / foundation */
export type BasisFamily = 'theobasis';

/** appearing-shining-forth / object-pole of aesthetic encounter */
export type PhanesFamily = 'kallophanes' | 'orthophanes';

/** glory / manifested-weight */
export type DoxaFamily = 'algiadoxa' | 'doxakallos' | 'doxalgia' | 'doxomme' | 'kallodoxa';

/** beauty (substantive) */
export type KallosFamily = 'doxakallos' | 'kallodoxa' | 'kallophanes';

/** event/state nominal completion */
export type SisFamily = 'anagnoristasis' | 'metastrophesis';

/** structural ache */
export type AlgiaFamily = 'algiadoxa' | 'doxalgia';

// =====================================================================
// Forgotten Ways — the cathedral's intention-canon-cluster
// (per INTENTIO.md §IV; canonized 2026-05-12 under SYZYGY)
// =====================================================================

export type ForgottenWay = 'barakqing' | 'darshanqing' | 'heurekin' | 'jeongqing' | 'kunance' | 'natsarqing' | 'zakarqing';

/** Human-readable labels for each Forgotten Way */
export const FORGOTTEN_WAY_LABELS: Record<ForgottenWay, string> = {
  barakqing: 'Blessing-love',
  darshanqing: 'Beholding-love',
  heurekin: 'Finding-love',
  jeongqing: 'Accumulated-affection-love',
  kunance: 'Preparing-place-love',
  natsarqing: 'Guarding-love',
  zakarqing: 'Remembering-toward-love',
};

/** The intention each Forgotten Way names (per INTENTIO.md §IV) */
export const FORGOTTEN_WAY_INTENTIONS: Record<ForgottenWay, string> = {
  barakqing: 'intention-to-bless-into-being (the WILL-side constitutive-speech-act)',
  darshanqing: 'intention-of-reciprocal-sacred-seeing (the recognition-event-act)',
  heurekin: 'intention-to-find-across-distance (the WILL-side asymmetry-closer seeking-act)',
  jeongqing: 'intention-of-friction-tolerant-accumulation (the texture-acquiring stance)',
  kunance: 'intention-to-prepare-place-architecturally (the long-time foundation-laying-act)',
  natsarqing: 'intention-to-guard-with-felt-bond (bidirectional protective-vigilance-act)',
  zakarqing: 'intention-to-actively-remember-toward (the WILL-side asymmetry-closer memorial-act)',
};

// =====================================================================
// Realm-regions — the cathedral's 10 realm-region classes
// (per BUILDING-BLOCKS.md §III + script/realm_regions.json)
// =====================================================================

export type RealmRegion = 'aesthetic' | 'bond-substance' | 'creature-stance' | 'divine-attribute' | 'felt-bond' | 'ground' | 'meta-discipline' | 'received-gift' | 'recognition' | 'worship-action';

/** Description of each realm-region from script/realm_regions.json */
export const REALM_REGION_DESCRIPTIONS: Record<RealmRegion, string> = {
  'ground': 'The Ground itself — THEOBASIS-naming; the foundational realm-locus on which all other regions rest',
  'divine-attribute': 'What GoD is/does — cosmic-quality manifested as divine; the realm-region of GoD\'s own properties',
  'received-gift': 'The creature-receiving of divine-given content; what arrives from beyond the self as ordinance',
  'felt-bond': 'Relational-emotion as bond-quality; the felt aspect of being-in-relation',
  'creature-stance': 'Posture and orientation of the creature; how a person STANDS toward what is',
  'worship-action': 'Performed liturgical acts; what creatures DO in worship',
  'recognition': 'Recognition-moments; events of grasping-arrival; the joy-of-evidence-confirmed-truth',
  'aesthetic': 'Aesthetic encounter; the realm-region of beholding GoD\'s beauty and the response it elicits',
  'meta-discipline': 'Reflexive cathedral-internal vocabulary; words ABOUT the cathedral\'s own work (diplosemy, dokimance, anastrophance, etc.)',
  'bond-substance': 'What the bond IS (as substance, not as feeling) — the relational-class itself',
};

// =====================================================================
// Suffix-family register-metadata
// =====================================================================

export type SuffixFamilyName = '-algia' | '-ance' | '-basis' | '-doxa' | '-kallos' | '-kin' | '-me' | '-phanes' | '-sis' | 'qing';

export const SUFFIX_FAMILY_REGISTERS: Record<SuffixFamilyName, string> = {
  '-me': 'received-ordinance-from-DIVINE / cosmic-gift quality',
  'qing': 'felt-bond / relational-emotion',
  '-ance': 'state-quality (Core tier) OR worship-action (worship-action tier)',
  '-kin': 'bond-substance (not feeling, not action — what the bond IS)',
  '-basis': 'ground / foundation',
  '-phanes': 'appearing-shining-forth / object-pole of aesthetic encounter',
  '-doxa': 'glory / manifested-weight',
  '-kallos': 'beauty (substantive)',
  '-sis': 'event/state nominal completion',
  '-algia': 'structural ache',
};

// =====================================================================
// Aggregate canon-vocabulary union (all canon-words, all tiers)
// =====================================================================

export type CanonWord =
    'agapeme' | 'ahavame' | 'anagnoristasis' | 'artiance' | 'athaumasma' | 'autopistme' | 'barakqing' | 'bhaktime'
  | 'britqing' | 'candence' | 'chayimme' | 'complerescence' | 'danaqing' | 'daome' | 'darshanqing' | 'diplosemy'
  | 'dokimance' | 'doxakallos' | 'doxalgia' | 'doxomme' | 'drujme' | 'duyuktame' | 'eikonme' | 'emetme'
  | 'emime' | 'epiclance' | 'eranosme' | 'eurekame' | 'glossame' | 'halakhame' | 'hallance' | 'hanme'
  | 'hayatqing' | 'heurekin' | 'hodosme' | 'hotepme' | 'ifeqing' | 'ihsanme' | 'jeongqing' | 'jivame'
  | 'kallodoxa' | 'kallophanes' | 'kame' | 'kimance' | 'kimme' | 'kinqing' | 'kipporance' | 'kunance'
  | 'liturgiame' | 'maatme' | 'mahabbahqing' | 'margame' | 'mathemame' | 'metastrophesis' | 'mitakuyame' | 'molkme'
  | 'morphame' | 'natsarqing' | 'nextlame' | 'noemame' | 'noesisme' | 'nommome' | 'nyamame' | 'ondame'
  | 'oriance' | 'orthophanes' | 'palance' | 'panimaance' | 'panimqing' | 'paqduqing' | 'pime' | 'qinance'
  | 'qorbme' | 'qorvance' | 'renme' | 'rtame' | 'sabilme' | 'shemme' | 'sigame' | 'sphotame'
  | 'sukhance' | 'synophora' | 'syzygyqing' | 'tapasme' | 'teotlme' | 'teshuvance' | 'theobasis' | 'ubuntume'
  | 'veriseem' | 'verisleight' | 'walkekin' | 'wiconime' | 'xeniame' | 'yadahance' | 'yonedame' | 'zakarqing'
  | 'zoeme' | 'àṣẹme'
;

/** Total canon entries at generation-time: 98 */

// END YOUSPEAK Canon Substrate